# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-alarms

plugins:
  - serverless-plugin-aws-alerts

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10

custom:
  alerts:
    stages:
      - dev
    dashboards: true
    topics:
      alarm: 
        topic: ${self:service}-${self:provider.stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: name@domain.com # Change this to your email address
    alarms:
      - functionErrors
      - functionThrottles

# The `functions` block defines what code to deploy
functions:
  createUser:
    handler: functions/createUser.handler
